name: run tests

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: pyth install
        uses: actions/setup-python@v4
        with:
          python-version: "3.12"

      - name: Install depend
        run: pip install -r requirements.txt

      - name: run
        run: pytest -q